import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider, Container } from "@chakra-ui/react";
import { theme } from "./theme/theme";
import { Nav } from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={theme}>
          <Nav />
          <Container
            justifyContent={"center"}
            textAlign={"center"}
            py={"6rem"}
            backgroundImage={"/images/splash/hd2-hero.jpg"}
            //backgroundSize={"contain"}
            backgroundRepeat={"repeat-y"}
            backgroundPosition={"0% 0%"}
            minH={"200vh"}
            px={{ base: ".5rem", lg: "3rem" }}
            minW={"100%"}
          >
            {children}
          </Container>
        </ChakraProvider>
      </body>
    </html>
  );
}
