export const missonTypeList = [
  { title: "Eradicate Swarm", value: "eradicate-swarm" },
  { title: "Emergency Evacuation", value: "emergency-evacuation" },
  { title: "Retrieve Valuable Data", value: "retrieve-valuable-data" },
  { title: "Blitz Search and Destroy", value: "blitz-search-and-destroy" },
  { title: "Enable E-710 Extraction", value: "enable-e-710-extraction" },
  { title: "Eliminate Bile Titan", value: "eliminate-bile-titan" },
  { title: "Purge Hatcheries", value: "purge-hatcheries" },
  { title: "Launch ICBM", value: "launch-icbm" },
  { title: "Upload Escape Pod Data ", value: "upload-escape-pod-data" },
  { title: "Eliminate Brood Commander", value: "eliminate-brood-commander" },
  { title: "Eliminate Charger", value: "eliminate-charger" },
  { title: "Spread Democracy", value: "spread-democracy" },
  {
    title: "Terminate Illegal Broadcast",
    value: "terminate-illegal-broadcast",
  },
  { title: "Search and Destroy", value: "search-and-destroy" },
  { title: "Sabotage Supply Bases", value: "sabotage-supply-bases" },
  { title: "Eradicate Automaton Forces", value: "eradicate-automaton-forces" },
  { title: "Sabotage Air Base", value: "sabotage-air-base" },
  { title: "Eliminate Automaton Hulk", value: "eliminate-automaton-hulk" },
  {
    title: "Eliminate Automaton Devastator",
    value: "eliminate-automaton-devastator",
  },
  {
    title: "Destroy Network Transmission",
    value: "destroy-network-transmission",
  },
  {
    title: "Retrieve Essential Personnel",
    value: "retrieve-essential-personnel",
  },
];
